version: '3'

services: 
  api-test:
    image: 'node:8.12.0-alpine'
    working_dir: '/home/api-test'
    volumes:
      - ./:/home/api-test
    command: "sh -c 'npm install && npm run dev'"
    depends_on:
      - api-db
    environment:
      NODE_ENV: development
    ports: 
      - 4001:4001
  api-db:
     image: 'mongo:4'
